id: P004428
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 11:20:41.328318
source_metadata:
  id: bdr:W8LS19126
  title: གསར་འགྱུར་རིག་པའི་གཞུང་ལུགས་ཀྱི་བསླབ་གཞི།
  author: ''
  volumes:
    e906d8b8da4d4471ae59c589112cbc39:
      image_group_id: I8LS19128
      title: ''
      volume_number: 1
      total_pages: 202
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
